version: '3.7'

networks:
  potternetwork:

x-service: &service
  networks:
    - potternetwork

services:

  app:
    <<: *service
    build:
      context: .
    ports:
      - 9090:9090
    depends_on:
      - postgres
      - redis
    environment:
      APP_SERVER_PORT: 9090
      SPRING_DATASOURCE_URL: jdbc:postgresql://${POST_HOST}:${POST_PORT}/${POST_DB}
      SPRING_DATASOURCE_USERNAME: ${POST_USER}
      SPRING_DATASOURCE_PASSWORD: ${POST_PASS}
      SPRING_REDIS_HOST: redis

  postgres:
    <<: *service
    image: library/postgres:latest
    ports:
      - 5432:5432
    environment:
      POSTGRES_PASSWORD: ${POST_PASS}
      POSTGRES_DB: ${POST_DB}

  redis:
    <<: *service
    image: library/redis:latest
    ports:
      - 6379:6379