server:
  port: ${app.server.port:7070}
  servlet:
    context-path: /api/v1
  error:
    include-stacktrace: never

spring:
  jpa:
    hibernate:
      ddl-auto: validate
    database-platform: org.hibernate.dialect.PostgreSQLDialect