apiVersion: v1
kind: Secret
metadata:
  name: app-keys
  namespace: dextratest
type: Opaque
data:
  jwt-secret: $JWT_SECRET
  jwt-expiration: $JWT_EXPIRATION
  db-url: $DB_URL
  db-user: $DB_USER
  db-pass: $DB_PASS
  redis-host: $REDIS_HOST
  integration-url: $INTEGRATION_URL
  integration-key: $INTEGRATION_KEY
  integration-houses-path: $INTEGRATION_HOUSES_PATH
